apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: traderx-dev
spec:
  selector:
    app: account-service
  ports:
  - name: http
    port: 18088
    targetPort: 18088
    protocol: TCP
  type: ClusterIP