apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: traderx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
        layer: backend
    spec:
      enableServiceLinks: false
      containers:
      - name: account-service
        image: ghcr.io/finos/traderx/account-service:latest
        ports:
        - containerPort: 18088
        env:
        - name: ACCOUNT_SERVICE_PORT
          value: "18088"
        - name: DATABASE_TCP_HOST
          value: "database"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"