apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-service
  namespace: traderx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-service
  template:
    metadata:
      labels:
        app: position-service
        layer: backend
    spec:
      containers:
      - name: position-service
        image: ghcr.io/finos/traderx/position-service:latest
        ports:
        - containerPort: 18090
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SERVER_PORT
          value: "18090"
        - name: REFERENCE_DATA_URL
          value: "http://reference-data:18085"
        - name: ACCOUNT_SERVICE_URL
          value: "http://account-service:18091"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"