apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-service
  namespace: traderx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-service
  template:
    metadata:
      labels:
        app: position-service
        layer: backend
    spec:
      enableServiceLinks: false
      containers:
      - name: position-service
        image: ghcr.io/finos/traderx/position-service:latest
        ports:
        - containerPort: 18090
        env:
        - name: DATABASE_TCP_HOST
          value: "database"
        - name: POSITION_SERVICE_PORT
          value: "18090"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:tcp://database:18082/traderx;DB_CLOSE_DELAY=-1"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.H2Dialect"
        livenessProbe:
          httpGet:
            path: /health/alive
            port: 18090
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 18090
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"