apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-data
  namespace: traderx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reference-data
  template:
    metadata:
      labels:
        app: reference-data
        layer: data
    spec:
      containers:
      - name: reference-data
        image: finos/traderx-reference-data:latest
        ports:
        - containerPort: 18085
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SERVER_PORT
          value: "18085"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"