apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-processor
  namespace: traderx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-processor
  template:
    metadata:
      labels:
        app: trade-processor
        layer: backend
    spec:
      containers:
      - name: trade-processor
        image: finos/traderx-trade-processor:latest
        env:
        - name: PYTHON_ENV
          value: "development"
        - name: TRADE_SERVICE_URL
          value: "http://trade-service:18092"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"