apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-feed
  namespace: traderx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-feed
  template:
    metadata:
      labels:
        app: trade-feed
        layer: backend
    spec:
      enableServiceLinks: false
      containers:
      - name: trade-feed
        image: ghcr.io/finos/traderx/trade-feed:latest
        ports:
        - containerPort: 18086
        env:
        - name: PORT
          value: "18086"
        - name: TRADE_FEED_PORT
          value: "18086"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"